mission_coordinator:
  waypoints_x: [ 40.0, 40.0,  0.0, 0.0] #[m]
  waypoints_y: [  0.0, 40.0, 40.0, 0.0] #[m]

  obstacles:
    start_x:        [20, 40, 20, 20, 0, 20 ] #[m]
    start_y:        [0, 20, 60, -20, 20, 40 ] #[m]
    start_theta:    [1.6, 4.8, 0, 0, -1, 3.5] #[rad]
    u:              [0.5, 0, 0, 0, 0, 0] #[m/s]
    v:              [0, 0, 0, 0, 0, 0] #[m/s]
    omega:          [0, 0, 0, 0, 0, 0] #[rad/s]
    major_semiaxis: [6, 10, 40, 40, 12, 4] #[m]
    minor_semiaxis: [10, 8, 3 ,3, 4, 8] #[m]

  frame_id: '/my_frame'
  verbose: true
