mission_coordinator:
  waypoints_x: [ 60.0, 60.0,  0.0, 0.0] #[m]
  waypoints_y: [  0.0, 60.0, 60.0, 0.0] #[m]

  obstacles:
    start_x:        [40,   60,   0,  30, 15, 65] #[m]
    start_y:        [0,    20,  30,  60,  0, 45] #[m]
    start_theta:    [1.6, 4.8,  -1, 3.5,  0,  0] #[rad]
    u:              [0.5,   0,   0,   0,  0,  0] #[m/s]
    v:              [0,     0,   0,   0,  0,  0] #[m/s]
    omega:          [0,     0,   0,   0,  0,  0] #[rad/s]
    major_semiaxis: [6,    10,  12,   4,  1,  5] #[m]
    minor_semiaxis: [10,    8,   4,   8,  1,  5] #[m]

  reference:
    velocity: 3.0

  frame_id: '/my_frame'
  verbose: true

Route_generator:
  k_max:         1.0 #
  gamma_max:     1.0 #
  final_time:    10 #
  safety_margin: 3.0

PID:
  max_theta_error:           0.5
  parallel_error_gain:       0.25
  perpendicular_error_gain:  2
  velocity_error_gain:       2
  
Ekf:
  disturbance: 
    fx1: -25
    fx2: -25
    fy1: 0
    fy2: 0
