## USB port
#port: /dev/nautonomous/imu
port: /dev/tty/USB0

##### Calibration ####
### accelerometer
accel_x_min: -302.0
accel_x_max: 269.0
accel_y_min: -296.0
accel_y_max: 297.0
accel_z_min: -313.0
accel_z_max: 316.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [0.244971, 3.95740, 0.470133]
magn_ellipsoid_transform: [[0.885247, 0.0480997, 0.0710702], [0.0480997, 0.940532, 0.0554746], [0.0710702, 0.0554746, 0.771029]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 33.25
gyro_average_offset_y: 36.37
gyro_average_offset_z: 25.83

